//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/DEBUG/InputCore/Inputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Inputs : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Inputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Inputs"",
    ""maps"": [
        {
            ""name"": ""TardigreBasicActions"",
            ""id"": ""e30d3461-2fb6-4e86-bfa9-2b7124b8007e"",
            ""actions"": [
                {
                    ""name"": ""LeftJoycon"",
                    ""type"": ""Value"",
                    ""id"": ""b13b0224-46dc-4f52-8185-02fbed8afd13"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""A"",
                    ""type"": ""Button"",
                    ""id"": ""47086f3c-3492-4a33-95b4-549ec0e9ae22"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""B"",
                    ""type"": ""Button"",
                    ""id"": ""ed664abb-c36d-4f35-9722-46b933314c58"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Y"",
                    ""type"": ""Button"",
                    ""id"": ""466e2f71-435d-4825-ae5d-545e22b2fde4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""X"",
                    ""type"": ""Button"",
                    ""id"": ""f6a2c4dd-306e-45a6-810f-2c6babe94557"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightTrigger"",
                    ""type"": ""Value"",
                    ""id"": ""03d8e4e0-8b81-4e53-b308-ed665fbd4b8b"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftTrigger"",
                    ""type"": ""Value"",
                    ""id"": ""9ed00a3e-eda1-4e54-8117-579d106e8869"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DPadUp"",
                    ""type"": ""Button"",
                    ""id"": ""8b4ca5af-5bbe-4341-9aa9-ca8608279811"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DPadDown"",
                    ""type"": ""Button"",
                    ""id"": ""8f41d29e-c86a-42e0-9ecf-4b617995a9f0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DPadLeft"",
                    ""type"": ""Button"",
                    ""id"": ""55982fc5-7092-4b92-9fce-e142a8e24366"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DPadRight"",
                    ""type"": ""Button"",
                    ""id"": ""87e6f294-90f3-4075-9bd3-b59726594f23"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftBumper"",
                    ""type"": ""Button"",
                    ""id"": ""16cda5bd-f213-4a48-b6c4-32f9290b391b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightBumper"",
                    ""type"": ""Button"",
                    ""id"": ""8e684788-342e-4a2a-94c3-0a1b9c9b34b1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""acce809d-a58d-408f-b53e-4bc6fb60b6d8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Start"",
                    ""type"": ""Button"",
                    ""id"": ""23ceb24f-54ae-49c2-ab7d-1da1a893198a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightJoycon"",
                    ""type"": ""Value"",
                    ""id"": ""504789a0-c336-4f01-b6e6-d46d79ae2658"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""726a3996-d486-45df-9159-7853049e68af"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftJoycon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""b69daefa-7c74-410b-9b29-86d4dce66736"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftJoycon"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""67b0f701-4616-4fd5-a09c-995bfbb67315"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftJoycon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""48d97ffc-b910-4960-97de-74ba75f2eb91"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftJoycon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""beaf4d69-d902-4032-b41b-46951414149d"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftJoycon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""75316bd4-2456-422f-ac7c-190b2b80be5d"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftJoycon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""6c91e167-dc48-4674-9ff2-75e8056b6741"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""001db050-a3c1-48f5-9981-53060b78303e"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5d89b405-2d43-4535-a681-d7dac8887267"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""B"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8abf9ae5-fd1a-44f2-8859-96a35552826b"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""B"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab83b4ff-2e9b-4f01-8f07-12df6e268c0b"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Y"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5a045741-83e4-4450-bb39-f4e03558e3f9"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Y"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d676ecbc-4caa-49b2-bc7a-c663eaf593b1"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""X"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""83c9819e-8fa6-4963-8531-106a4e2fd831"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""X"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c4a539a-98f6-4ccf-944c-1ce423f903a0"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b264680a-8d3a-42ac-b2be-caa7ad354fce"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""381dd1d4-e823-4719-b8e5-d9bad724d541"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9c10b004-cafe-4b0a-8397-4fedcbb3f9b8"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8f24177f-caef-4c85-b39e-f310dafbd8bb"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPadUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6418393b-17cd-4f51-9bf0-df7a040fbf61"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPadUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e8bff71b-5826-4cdb-a02f-d0bc26c79304"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPadDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7b3865f7-1b77-45a5-b84d-b0bda5c9e953"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPadDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""692f7a6b-3f65-4608-973f-6740fa133614"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPadLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c641703-14f0-480e-b971-52bec68cddf3"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPadLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7b0a57a9-6482-4a65-a1aa-e5aa37940daf"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPadRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b576614-969c-42f2-ad56-edbae2050404"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPadRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd22a049-b950-4085-955e-56e1baa1a311"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftBumper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f5386b40-1f72-45f9-be58-2c6ad6c6d603"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftBumper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""49df5fab-8e1f-44e4-adf1-757e13d97c25"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightBumper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e94d8992-f30a-447b-985f-aa79b44e1984"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightBumper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aba18825-d893-40a1-8190-947628af08cb"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eebb9ed1-97f3-4a47-ae47-129b6e9f7dd4"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""403069c1-e0fb-4b3e-aab2-17181f2bf8af"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""35579b34-cc3e-4001-a54b-12e20aa7fe33"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1ac9415d-16b5-4860-b51c-0d9a55455d65"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightJoycon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Arrows"",
                    ""id"": ""901f2be0-da91-4386-b76b-d9be7ab36804"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightJoycon"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6348943e-90b3-4d49-bb56-634c3ac40576"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightJoycon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f5f7a509-39b9-4f4a-9f72-f97762c297d9"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightJoycon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""09310632-8c23-4463-9b39-d1be1ccbee76"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightJoycon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""3f9123ed-0cb1-491a-92fc-1d699be79e07"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightJoycon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // TardigreBasicActions
        m_TardigreBasicActions = asset.FindActionMap("TardigreBasicActions", throwIfNotFound: true);
        m_TardigreBasicActions_LeftJoycon = m_TardigreBasicActions.FindAction("LeftJoycon", throwIfNotFound: true);
        m_TardigreBasicActions_A = m_TardigreBasicActions.FindAction("A", throwIfNotFound: true);
        m_TardigreBasicActions_B = m_TardigreBasicActions.FindAction("B", throwIfNotFound: true);
        m_TardigreBasicActions_Y = m_TardigreBasicActions.FindAction("Y", throwIfNotFound: true);
        m_TardigreBasicActions_X = m_TardigreBasicActions.FindAction("X", throwIfNotFound: true);
        m_TardigreBasicActions_RightTrigger = m_TardigreBasicActions.FindAction("RightTrigger", throwIfNotFound: true);
        m_TardigreBasicActions_LeftTrigger = m_TardigreBasicActions.FindAction("LeftTrigger", throwIfNotFound: true);
        m_TardigreBasicActions_DPadUp = m_TardigreBasicActions.FindAction("DPadUp", throwIfNotFound: true);
        m_TardigreBasicActions_DPadDown = m_TardigreBasicActions.FindAction("DPadDown", throwIfNotFound: true);
        m_TardigreBasicActions_DPadLeft = m_TardigreBasicActions.FindAction("DPadLeft", throwIfNotFound: true);
        m_TardigreBasicActions_DPadRight = m_TardigreBasicActions.FindAction("DPadRight", throwIfNotFound: true);
        m_TardigreBasicActions_LeftBumper = m_TardigreBasicActions.FindAction("LeftBumper", throwIfNotFound: true);
        m_TardigreBasicActions_RightBumper = m_TardigreBasicActions.FindAction("RightBumper", throwIfNotFound: true);
        m_TardigreBasicActions_Select = m_TardigreBasicActions.FindAction("Select", throwIfNotFound: true);
        m_TardigreBasicActions_Start = m_TardigreBasicActions.FindAction("Start", throwIfNotFound: true);
        m_TardigreBasicActions_RightJoycon = m_TardigreBasicActions.FindAction("RightJoycon", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // TardigreBasicActions
    private readonly InputActionMap m_TardigreBasicActions;
    private ITardigreBasicActionsActions m_TardigreBasicActionsActionsCallbackInterface;
    private readonly InputAction m_TardigreBasicActions_LeftJoycon;
    private readonly InputAction m_TardigreBasicActions_A;
    private readonly InputAction m_TardigreBasicActions_B;
    private readonly InputAction m_TardigreBasicActions_Y;
    private readonly InputAction m_TardigreBasicActions_X;
    private readonly InputAction m_TardigreBasicActions_RightTrigger;
    private readonly InputAction m_TardigreBasicActions_LeftTrigger;
    private readonly InputAction m_TardigreBasicActions_DPadUp;
    private readonly InputAction m_TardigreBasicActions_DPadDown;
    private readonly InputAction m_TardigreBasicActions_DPadLeft;
    private readonly InputAction m_TardigreBasicActions_DPadRight;
    private readonly InputAction m_TardigreBasicActions_LeftBumper;
    private readonly InputAction m_TardigreBasicActions_RightBumper;
    private readonly InputAction m_TardigreBasicActions_Select;
    private readonly InputAction m_TardigreBasicActions_Start;
    private readonly InputAction m_TardigreBasicActions_RightJoycon;
    public struct TardigreBasicActionsActions
    {
        private @Inputs m_Wrapper;
        public TardigreBasicActionsActions(@Inputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @LeftJoycon => m_Wrapper.m_TardigreBasicActions_LeftJoycon;
        public InputAction @A => m_Wrapper.m_TardigreBasicActions_A;
        public InputAction @B => m_Wrapper.m_TardigreBasicActions_B;
        public InputAction @Y => m_Wrapper.m_TardigreBasicActions_Y;
        public InputAction @X => m_Wrapper.m_TardigreBasicActions_X;
        public InputAction @RightTrigger => m_Wrapper.m_TardigreBasicActions_RightTrigger;
        public InputAction @LeftTrigger => m_Wrapper.m_TardigreBasicActions_LeftTrigger;
        public InputAction @DPadUp => m_Wrapper.m_TardigreBasicActions_DPadUp;
        public InputAction @DPadDown => m_Wrapper.m_TardigreBasicActions_DPadDown;
        public InputAction @DPadLeft => m_Wrapper.m_TardigreBasicActions_DPadLeft;
        public InputAction @DPadRight => m_Wrapper.m_TardigreBasicActions_DPadRight;
        public InputAction @LeftBumper => m_Wrapper.m_TardigreBasicActions_LeftBumper;
        public InputAction @RightBumper => m_Wrapper.m_TardigreBasicActions_RightBumper;
        public InputAction @Select => m_Wrapper.m_TardigreBasicActions_Select;
        public InputAction @Start => m_Wrapper.m_TardigreBasicActions_Start;
        public InputAction @RightJoycon => m_Wrapper.m_TardigreBasicActions_RightJoycon;
        public InputActionMap Get() { return m_Wrapper.m_TardigreBasicActions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TardigreBasicActionsActions set) { return set.Get(); }
        public void SetCallbacks(ITardigreBasicActionsActions instance)
        {
            if (m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface != null)
            {
                @LeftJoycon.started -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnLeftJoycon;
                @LeftJoycon.performed -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnLeftJoycon;
                @LeftJoycon.canceled -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnLeftJoycon;
                @A.started -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnA;
                @A.performed -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnA;
                @A.canceled -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnA;
                @B.started -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnB;
                @B.performed -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnB;
                @B.canceled -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnB;
                @Y.started -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnY;
                @Y.performed -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnY;
                @Y.canceled -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnY;
                @X.started -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnX;
                @X.performed -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnX;
                @X.canceled -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnX;
                @RightTrigger.started -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnRightTrigger;
                @RightTrigger.performed -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnRightTrigger;
                @RightTrigger.canceled -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnRightTrigger;
                @LeftTrigger.started -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnLeftTrigger;
                @LeftTrigger.performed -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnLeftTrigger;
                @LeftTrigger.canceled -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnLeftTrigger;
                @DPadUp.started -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnDPadUp;
                @DPadUp.performed -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnDPadUp;
                @DPadUp.canceled -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnDPadUp;
                @DPadDown.started -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnDPadDown;
                @DPadDown.performed -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnDPadDown;
                @DPadDown.canceled -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnDPadDown;
                @DPadLeft.started -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnDPadLeft;
                @DPadLeft.performed -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnDPadLeft;
                @DPadLeft.canceled -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnDPadLeft;
                @DPadRight.started -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnDPadRight;
                @DPadRight.performed -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnDPadRight;
                @DPadRight.canceled -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnDPadRight;
                @LeftBumper.started -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnLeftBumper;
                @LeftBumper.performed -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnLeftBumper;
                @LeftBumper.canceled -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnLeftBumper;
                @RightBumper.started -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnRightBumper;
                @RightBumper.performed -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnRightBumper;
                @RightBumper.canceled -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnRightBumper;
                @Select.started -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnSelect;
                @Select.performed -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnSelect;
                @Select.canceled -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnSelect;
                @Start.started -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnStart;
                @Start.performed -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnStart;
                @Start.canceled -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnStart;
                @RightJoycon.started -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnRightJoycon;
                @RightJoycon.performed -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnRightJoycon;
                @RightJoycon.canceled -= m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface.OnRightJoycon;
            }
            m_Wrapper.m_TardigreBasicActionsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @LeftJoycon.started += instance.OnLeftJoycon;
                @LeftJoycon.performed += instance.OnLeftJoycon;
                @LeftJoycon.canceled += instance.OnLeftJoycon;
                @A.started += instance.OnA;
                @A.performed += instance.OnA;
                @A.canceled += instance.OnA;
                @B.started += instance.OnB;
                @B.performed += instance.OnB;
                @B.canceled += instance.OnB;
                @Y.started += instance.OnY;
                @Y.performed += instance.OnY;
                @Y.canceled += instance.OnY;
                @X.started += instance.OnX;
                @X.performed += instance.OnX;
                @X.canceled += instance.OnX;
                @RightTrigger.started += instance.OnRightTrigger;
                @RightTrigger.performed += instance.OnRightTrigger;
                @RightTrigger.canceled += instance.OnRightTrigger;
                @LeftTrigger.started += instance.OnLeftTrigger;
                @LeftTrigger.performed += instance.OnLeftTrigger;
                @LeftTrigger.canceled += instance.OnLeftTrigger;
                @DPadUp.started += instance.OnDPadUp;
                @DPadUp.performed += instance.OnDPadUp;
                @DPadUp.canceled += instance.OnDPadUp;
                @DPadDown.started += instance.OnDPadDown;
                @DPadDown.performed += instance.OnDPadDown;
                @DPadDown.canceled += instance.OnDPadDown;
                @DPadLeft.started += instance.OnDPadLeft;
                @DPadLeft.performed += instance.OnDPadLeft;
                @DPadLeft.canceled += instance.OnDPadLeft;
                @DPadRight.started += instance.OnDPadRight;
                @DPadRight.performed += instance.OnDPadRight;
                @DPadRight.canceled += instance.OnDPadRight;
                @LeftBumper.started += instance.OnLeftBumper;
                @LeftBumper.performed += instance.OnLeftBumper;
                @LeftBumper.canceled += instance.OnLeftBumper;
                @RightBumper.started += instance.OnRightBumper;
                @RightBumper.performed += instance.OnRightBumper;
                @RightBumper.canceled += instance.OnRightBumper;
                @Select.started += instance.OnSelect;
                @Select.performed += instance.OnSelect;
                @Select.canceled += instance.OnSelect;
                @Start.started += instance.OnStart;
                @Start.performed += instance.OnStart;
                @Start.canceled += instance.OnStart;
                @RightJoycon.started += instance.OnRightJoycon;
                @RightJoycon.performed += instance.OnRightJoycon;
                @RightJoycon.canceled += instance.OnRightJoycon;
            }
        }
    }
    public TardigreBasicActionsActions @TardigreBasicActions => new TardigreBasicActionsActions(this);
    public interface ITardigreBasicActionsActions
    {
        void OnLeftJoycon(InputAction.CallbackContext context);
        void OnA(InputAction.CallbackContext context);
        void OnB(InputAction.CallbackContext context);
        void OnY(InputAction.CallbackContext context);
        void OnX(InputAction.CallbackContext context);
        void OnRightTrigger(InputAction.CallbackContext context);
        void OnLeftTrigger(InputAction.CallbackContext context);
        void OnDPadUp(InputAction.CallbackContext context);
        void OnDPadDown(InputAction.CallbackContext context);
        void OnDPadLeft(InputAction.CallbackContext context);
        void OnDPadRight(InputAction.CallbackContext context);
        void OnLeftBumper(InputAction.CallbackContext context);
        void OnRightBumper(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
        void OnStart(InputAction.CallbackContext context);
        void OnRightJoycon(InputAction.CallbackContext context);
    }
}
